// actions types
export const AC_TOPIC_GET_LIST = 'AC_TOPIC_GET_LIST';
export const AC_DETAIL_GET_LIST = 'AC_DETAIL_GET_LIST';

// mutations types
export const MT_TOPIC_CLEAR_LIST = 'MT_TOPIC_CLEAR_LIST';
export const MT_TOPIC_ADD_LIST = 'MT_TOPIC_ADD_LIST';
export const MT_TOPIC_MOD_REFRESHING = 'MT_TOPIC_MOD_REFRESHING';

export const MT_DETAIL_CLEAR_LIST = 'MT_DETAIL_CLEAR_LIST';
export const MT_DETAIL_ADD_LIST = 'MT_DETAIL_ADD_LIST';

//  getters types
export const ST_BASEURL = 'ST_BASEURL';
export const ST_BASEURL_PIC = 'ST_BASEURL_PIC';

export const ST_TOPIC_LIST = 'ST_TOPIC_LIST';
export const ST_TOPIC_REFRESHING = 'ST_TOPIC_REFRESHING';
export const ST_TOPIC_LOADING = 'ST_TOPIC_LOADING';
export const ST_TOPIC_SNACKBAR = 'ST_TOPIC_SNACKBAR';
export const ST_TOPIC_PAGE = 'ST_TOPIC_PAGE';

export const ST_DETAIL_ALL = 'ST_DETAIL_ALL';
export const ST_DETAIL_LIST = 'ST_DETAIL_LIST';
export const ST_DETAIL_SUBJECT = 'ST_DETAIL_SUBJECT';
export const ST_DETAIL_LOADING = 'ST_DETAIL_LOADING';
export const ST_DETAIL_SNACKBAR = 'ST_DETAIL_SNACKBAR';
export const ST_DETAIL_PAGE = 'ST_DETAIL_PAGE';
export const ST_DETAIL_TOTAL = 'ST_DETAIL_TOTAL';
